stages:
  featurize:
    cmd: python scripts/featurize.py
    deps:
      - scripts/featurize.py
      - src/features/feature_engineering.py
      - data/raw/creditcard.csv
    outs:
      - data/processed/features.parquet:
          cache: true
    params:
      - configs/model_config.yaml:
          - feature_engineering

  train:
    cmd: python scripts/train.py
    deps:
      - scripts/train.py
      - src/models/train.py
      - src/models/baseline.py
      - src/features/feature_engineering.py
      - data/processed/features.parquet
      - configs/model_config.yaml
    outs:
      - data/processed/eval_metrics.json:
          cache: false
    params:
      - configs/model_config.yaml:
          - random_forest
          - mlp
          - training

  evaluate:
    cmd: python scripts/evaluate.py
    deps:
      - scripts/evaluate.py
      - data/processed/eval_metrics.json
